name: Testing Workflow
on:
  push:
    branches: [ testing ]

jobs:
  job_one:
    name: Testing
    runs-on: ubuntu-latest
    steps:
    - name: testing Oceanic Connections server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: 143.198.9.78
        username: root
        key: ${{ secrets.SSH_SECRET }}
        port: 22
        script: |
          cd ..
          cd var/www/html
          git pull origin main
          git status
